### ISSUE TITLE
[1.18.2] Vanilla ores not generating for some reason

### ISSUE THREAD

**Issue by Proxwian** [CannoliCatfish/project-rankine#309] opened 2022-08-06 14:46 UTC
I'm using rankine-1.18.2-1.3.4-hotfix1.jar for forge. Also mods like OreTweak or others then can configure ore spawning does not affecting ore generating. So world is unplayable without vanilla ores (coal, iron, redstone, diamond, etc.)

**Comment by CannoliCatfish** [comment] 2022-08-06 22:48
By default, vanilla ores are disabled in Project Rankine. Vanilla ores can be optionally generated via a config setting in rankine_common.toml, but are not required for progression by default. 

Our ore features also are tweaked separately via our config as well (due to the features having their own unique capabilities compared to a regular ore feature), and likely will be unable to be tweaked by external mods.

If there is an issue with progression that you found as a result of not being able to use vanilla ores or there are other generation issues, please describe the issue further. Otherwise, please let us know if the issue is resolved and we will close it.

**Comment by CannoliCatfish** [comment] 2022-08-16 18:02
Closed as issue is based on intended functionality.

**Closed as completed by CannoliCatfish** 2022-08-16 18:02 UTC
Labels: question, intended
